verbose: true
base_link: base_link
models:
 - name: arm
   type: chain
   frame: wrist_roll_link
 - name: camera
   type: camera3d
   frame: head_camera_rgb_optical_frame
   topic: /head_camera/depth_registered/points
 - name: camera_ground
   type: camera3d
   frame: head_camera_rgb_optical_frame
   topic: /head_camera/depth_registered/points
 - name: camera_robot
   type: camera3d
   frame: head_camera_rgb_optical_frame
   topic: /head_camera/depth_registered/points
free_params:
 - camera_fx
 - camera_fy
 - camera_cx
 - camera_cy
 - camera_z_offset
 - camera_z_scaling
free_frames:
 - name: head_camera_rgb_joint
   x: false
   y: false
   z: false
   roll: true
   pitch: true
   yaw: true
 - name: head_pan_joint
   x: false
   y: false
   z: false
   roll: false
   pitch: false
   yaw: false
error_blocks:
 - name: base_mesh_alignment
   type: chain3d_to_mesh
   model_a: camera_robot
   link_name: base_link
 - name: ground_plane
   type: chain3d_to_plane
   model_a: camera_ground
   a: 0.0
   b: 0.0
   c: 1.0
   d: 0.0
   scale: 1.0
 - name: restrict_camera
   type: outrageous
   param: head_camera_rgb_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
