amcl:
  ros__parameters:
    alpha1: 0.1
    alpha2: 0.2
    alpha3: 0.3
    alpha4: 0.2
    base_frame_id: "base_link"
    global_frame_id: "map"
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    robot_model_type: "differential"
    tf_broadcast: true
    z_hit: 0.6
    z_max: 0.05
    z_rand: 0.3
    z_short: 0.05

map_server:
  ros__parameters:
    yaml_filename: "map.yaml"
