ubr_driver:
  ros__parameters:
    default_controllers:
      - "arm_controller.gravity_compensation"
    arm_controller:
      gravity_compensation:
        type: "robot_controllers/GravityCompensation"
        root: "torso_lift_link"
        tip: "gripper_link"
        autostart: true
